-- MySQL Script generated by MySQL Workbench
-- 05/31/23 20:40:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AGENCIA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AGENCIA` ;

-- -----------------------------------------------------
-- Schema AGENCIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AGENCIA` DEFAULT CHARACTER SET utf8 ;
USE `AGENCIA` ;

-- -----------------------------------------------------
-- Table `AGENCIA`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENCIA`.`clientes` ;

CREATE TABLE IF NOT EXISTS `AGENCIA`.`clientes` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo_doc` VARCHAR(30) NOT NULL,
  `num_celular` DOUBLE NOT NULL,
  `fecha_nac` DATE NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AGENCIA`.`estadia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENCIA`.`estadia` ;

CREATE TABLE IF NOT EXISTS `AGENCIA`.`estadia` (
  `idEstadia` INT NOT NULL AUTO_INCREMENT,
  `medio` VARCHAR(45) NOT NULL,
  `tipo_estadia` VARCHAR(45) NOT NULL,
  `caracteristicas` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `huespedes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstadia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AGENCIA`.`reshotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENCIA`.`reshotel` ;

CREATE TABLE IF NOT EXISTS `AGENCIA`.`reshotel` (
  `idreshotel` INT NOT NULL,
  `fechareserva` DATE NOT NULL,
  `num_dias` INT(11) NOT NULL,
  `estadia_idEstadia` INT NOT NULL,
  `clientes_cedula` INT NOT NULL,
  PRIMARY KEY (`idreshotel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AGENCIA`.`transporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENCIA`.`transporte` ;

CREATE TABLE IF NOT EXISTS `AGENCIA`.`transporte` (
  `idtransporte` INT NOT NULL AUTO_INCREMENT,
  `lu_salida` VARCHAR(45) NOT NULL,
  `lu_destino` VARCHAR(45) NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `fecha_regreso` DATE NOT NULL,
  `hora_salida` TIME NOT NULL,
  `hora_regreso` TIME NOT NULL,
  `medio_trans` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtransporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AGENCIA`.`restransporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENCIA`.`restransporte` ;

CREATE TABLE IF NOT EXISTS `AGENCIA`.`restransporte` (
  `idrestransporte` INT NOT NULL,
  `fechareserva` DATE NOT NULL,
  `numdias` INT(11) NOT NULL,
  `clientes_cedula` INT NOT NULL,
  `transporte_idtransporte` INT NOT NULL,
  PRIMARY KEY (`idrestransporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
